### ISSUE TITLE
How to use GUIDEseqAnalysis function for multiple gRNAs.

### ISSUE THREAD

**Issue by svermai** [LihuaJulieZhu/GUIDEseq#4]
Hi @LihuaJulieZhu ,
Hope you are doing good, I wants to know how to run Guideseqanalysis function for multiple gRNAs, In document it is return that the
gRNA.file file containing one or more gRNAs in fasta format, So i created one fasta file which looks like:-

```
>HEK239_site4
GGCACTGCGGCTGGAGGTGG
>EMX1
GAGTCCGAGCAGAAGAAGAA
```

Now both gRNAs will have different PAM sequences GGG (HEK)and GAA (EMX1) how can i setup this in PAM argument in Guideseqanalysis function . 
Can you please help me to resolve this doubt for multiple gRNAs sequnces.

**Comment by LihuaJulieZhu** [comment]
Hi Shubham,

Thanks for the inquiry!

Did you use two different gRNAs for two different GUIDEseq experiments?

·         If yes, you can simply run GUIDEseqAnalysis twice using one of the following two gRNA files.



gRNAfile1.fa

 >HEK239_site4

GGCACTGCGGCTGGAGGTGG



gRNAfile2.fa

>EMX1

GAGTCCGAGCAGAAGAAGAA


  *   If not, you can run the analysis step by step according to https://bioconductor.org/packages/release/bioc/vignettes/GUIDEseq/inst/doc/GUIDEseq.pdf.
  *   In step 4, you will run offTargetAnalysisOfPeakRegions twice with one gRNA file at a time.

Best,
Julie

From: Shubham Verma ***@***.***>
Date: Monday, October 24, 2022 at 5:49 AM
To: LihuaJulieZhu/GUIDEseq ***@***.***>
Cc: Zhu, Lihua (Julie) ***@***.***>, Mention ***@***.***>
Subject: [LihuaJulieZhu/GUIDEseq] How to use GUIDEseqAnalysis function for multiple gRNAs. (Issue #4)

Hi @LihuaJulieZhu<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLihuaJulieZhu&data=05%7C01%7Cjulie.zhu%40umassmed.edu%7Cc161ed30d6a543db516308dab5a51a82%7Cee9155fe2da34378a6c44405faf57b2e%7C0%7C0%7C638022017970347317%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pk9i1m%2FL0a2U7%2BLwngmEpCl7yC3u6gHGPqtVJPtwA%2F8%3D&reserved=0> ,
Hope you are doing good, I wants to know how to run Guideseqanalysis function for multiple gRNAs, In document it is return that the
gRNA.file file containing one or more gRNAs in fasta format, So i created one fasta file which looks like:-

>HEK239_site4

GGCACTGCGGCTGGAGGTGG

>EMX1

GAGTCCGAGCAGAAGAAGAA

Now both gRNAs will have different PAM sequences GGG (HEK)and GAA (EMX1) how can i setup this in PAM argument in Guideseqanalysis function .
Can you please help me to resolve this doubt for multiple gRNAs sequnces.

**Comment by svermai** [comment]
@LihuaJulieZhu 
I want to use two different gRNAs for single GUIDEseq experiments, So Is there any way were i can use only Guideseqanalysis function for two different gRNAs at the same time.

**Comment by LihuaJulieZhu** [comment]
Not with different PAM sequences.

Best regards,

Julie
________________________________

**Comment by svermai** [comment]
okay Thank you
